-- 문제 설명
-- https://programmers.co.kr/learn/courses/30/lessons/59042

SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 20
ORDER BY HOUR ASC;